### ISSUE TITLE
Running exo service add with an existing name overwrites existing files

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#106]

**Comment by arekkas** [comment]
this causes further exo commands to fail (see #108) because:

```
name: editor-platform
description: 
version: 0.0.1

services:
  blob-go:
    location: ./blob-go
    location: ./blob-go

```
