### ISSUE TITLE
`exo create service` creates service in parent directory instead of current directory

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#156]
`exo create service` creates service in the parent directory instead of the current directory. I am using the windows CLI

**Comment by arekkas** [comment]
This is what my application.yml file looksl ike after `exo create service`:

```
name: editor-platform
description: 
version: 0.0.1

services:
  identity:
    location: ../identity
```
